<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.example.com/demoSchema"
xmlns:tns="http://www.example.com/demoSchema"
elementFormDefault="qualified">
    <element name="character">
        <complexType>
            <sequence>
                <element name="marine" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="salary" type="decimal"/>
                        </sequence>
                        <attribute name="id" type="ID" use="required"/>
                        <attribute name="lang" type="string" default="Java"/>
                        <attribute name="try" type="string" use="optional"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>
